/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false ../../worker-configuration.d.ts` (hash: 9c65bc9a6794280c2a3579ef9e5640cb)
interface __BaseEnv_Env {
	FIRMWARE_BUCKET: R2Bucket;
	ALLOWED_ORIGINS: string;
	ESP32_INCLUDE_PRERELEASES: string;
	STM32_ACCESS_MODE: string;
	STM32_INCLUDE_PRERELEASES: string;
	STM32_DOWNLOAD_TOKEN_TTL_SECONDS: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS" | "ESP32_INCLUDE_PRERELEASES" | "STM32_ACCESS_MODE" | "STM32_INCLUDE_PRERELEASES" | "STM32_DOWNLOAD_TOKEN_TTL_SECONDS">> {}
}
