import type { ComponentProps } from 'react';
import BLESettingsDrawer from '../../src/components/BLESettingsDrawer';
const now = Date.UTC(2026, 7, 8, 12, 0, 0);
const noop = () => undefined;
const noopAsync = async () => undefined;
const capabilitiesStatus = {
    protocolVersion: 1,
    flags0: 0xff,
    flags1: 0xff,
    flags2: 0xff,
    flags3: 0x01,
    interfaceRevision: 0x0e,
    maxMeasurementNotifyHz: 10,
    diagnosticPollHintSeconds: 2,
    currentTime: true,
    deviceInfo: true,
    cardStatus: true,
    cardLogControl: true,
    deviceMode: true,
    stm32FirmwareVersion: true,
    i2cConfigControl: true,
    sampleMetadata: true,
    deviceHealth: true,
    cardLogDetail: true,
    cardLogSettings: true,
    capabilities: true,
    windNotifications: true,
    rtcReadWrite: true,
    i2cConfigWrite: true,
    cardLogWrite: true,
    deviceIdentify: true,
    ledBrightness: true,
    ledWindReactive: true,
    otaControl: true,
    resetControl: true,
    stm32UpdateControl: true,
    timezoneConfig: true,
} as const;
const otaControlStatus = {
    protocolVersion: 1,
    lastOpCode: 0,
    lastOp: 'read',
    resultCode: 0,
    result: 'ok',
    stateCode: 1,
    progress: 32,
    flags: 0x05,
    portalActive: false,
    updating: false,
    hasCredentials: true,
    error: false,
    uploadedBytes: 32768,
    totalBytes: 102400,
    remainingSeconds: 180,
    nodeId: 101,
    ssid: 'ULSA-EVO-UPDATE-101',
    password: 'layout-test-password',
    token: 'layout-test-token',
    ip: '192.168.4.1',
} as const;
export const drawerLayoutFixtureProps: ComponentProps<typeof BLESettingsDrawer> = {
    isOpen: true,
    entryMode: 'settled',
    onDismiss: noop,
    connectionState: 'connected',
    dataState: 'live',
    connectedDevice: {
        deviceId: '297CA361-44F1-293C-AF16-B3D67276B9B7',
        name: 'ULSA EVO #101',
        nodeId: 101,
    },
    deviceInfo: {
        softwareRevision: 'r2.fixture.demo',
        firmwareRevision: 'esp32-2026.08.08-layout-regression',
        manufacturerName: 'STRVSN',
        modelNumber: 'ULSA EVO',
    },
    stm32FirmwareVersion: {
        protocolVersion: 1,
        flags: 0x07,
        i2cClientPresent: true,
        detected: true,
        readOk: true,
        localError: 0,
        regVersion: 6,
        firmwareVersionRaw: 20260808,
        firmwareVersion: '20260808',
    },
    stm32FirmwareVersionLastReadAt: now,
    sampleMetadataStatus: {
        protocolVersion: 1,
        flags: 0x0f,
        valid: true,
        sourceI2c: true,
        sourceUart: false,
        stale: true,
        sequence: 123456789,
        esp32TimestampMs: 987654321,
        sourceCode: 1,
        source: 'i2c',
        remoteStatus: 0x20,
        remoteError: 0,
        localError: 0,
    },
    sampleMetadataLastReadAt: now,
    deviceHealthStatus: {
        protocolVersion: 2,
        flags: 0xff,
        bleConnected: true,
        i2cDetected: true,
        rtcAvailable: true,
        cardAvailable: true,
        loggingEnabled: true,
        configDirty: true,
        rebootRequired: true,
        errorActive: true,
        esp32ModeCode: 1,
        esp32LastError: 0x11,
        stm32RegisterVersion: 6,
        stm32Status: 0x22,
        stm32LastError: 0x33,
        localI2cError: 0x44,
        cardState: 4,
        cardStopReason: 2,
        rtcFlags: 0x07,
        rtcPresent: true,
        rtcRunning: true,
        rtcTimeValid: true,
        rtcVoltageLow: false,
        rtcClockStopped: false,
    },
    deviceHealthLastReadAt: now,
    capabilitiesStatus,
    capabilitiesLastReadAt: now,
    ledBrightnessStatus: { brightness: 200 },
    ledBrightnessSupported: true,
    ledBrightnessBusy: false,
    ledWindReactiveStatus: {
        protocolVersion: 1,
        lastOpCode: 0,
        lastOp: 'read',
        resultCode: 0,
        result: 'ok',
        flags: 0x07,
        enabled: true,
        active: true,
        persisted: true,
        theme: 'tide',
    },
    ledWindReactiveSupported: true,
    ledWindReactiveBusy: false,
    deviceResetStatus: {
        protocolVersion: 1,
        lastOpCode: 0,
        lastOp: 'read',
        resultCode: 0,
        result: 'ok',
        flags: 0,
        esp32ResetPending: false,
        stm32ResetPending: false,
        esp32Rebooting: false,
        stm32Resetting: false,
        targetCode: 0,
        target: 'none',
    },
    deviceResetSupported: true,
    deviceResetBusy: false,
    otaControlStatus,
    otaControlBusy: false,
    stm32UpdateControlStatus: { ...otaControlStatus },
    stm32UpdateControlBusy: false,
    cardStatus: {
        cardState: 4,
        usagePercent: 68.4,
        freeSpaceMB: 2528,
        totalSpaceMB: 8000,
        usedSpaceMB: 5472,
        cardTypeCode: 4,
        cardType: 'cardhc',
    },
    cardStatusLastReadAt: now,
    cardLogDetailStatus: {
        protocolVersion: 1,
        flags: 0xff,
        cardAvailable: true,
        loggingEnabled: true,
        canLog: true,
        fileOpen: true,
        rtcTimestamping: true,
        slowWrite: true,
        errorStop: true,
        cardState: 4,
        stopReasonCode: 2,
        logRateHz: 10,
        logCount: 987654,
        flushCount: 12345,
        bufferedBytes: 65535,
        lastWriteDurationMs: 4321,
        lastLogAgeSeconds: 3,
    },
    cardLogDetailLastReadAt: now,
    cardLogSettingsStatus: {
        protocolVersion: 3,
        lastOpCode: 0,
        lastOp: 'read',
        resultCode: 0,
        result: 'ok',
        flags: 0x03,
        persisted: true,
        stmIntervalKnown: true,
        defaultInterval: false,
        autoStartEnabled: true,
        currentIntervalMs: 200,
        minIntervalMs: 100,
        maxIntervalMs: 600000,
        stm32IntervalMs: 100,
    },
    cardLogSettingsLastReadAt: now,
    cardLogSettingsBusy: false,
    browserLogIntervalMs: 100,
    browserLogStatus: {
        active: true,
        sessionId: 'layout-regression-session-with-a-long-identifier',
        rowCount: 987654,
        segmentCount: 123,
        completedSegmentCount: 122,
        currentSegmentStartedAt: now - 60000,
        lastSampleAt: now,
        bufferedBytes: 65535,
        storedSessionCount: 123,
        storedSegmentCount: 456,
        storedRowCount: 987654,
        storedBytes: 123456789,
        hasExportableData: true,
        sessions: [{
                sessionId: 'layout-regression-session-with-a-long-identifier',
                startedAt: now - 60000,
                endedAt: null,
                lastActivityAt: now,
                retentionAnchorAt: now,
                expiresAt: now + 30 * 24 * 60 * 60 * 1000,
                rowCount: 987654,
                segmentCount: 123,
                sizeBytes: 123456789,
                completed: false,
            }],
        retentionDays: 30,
        maxStoredBytes: 100 * 1024 * 1024,
        minFreeBytes: 16 * 1024 * 1024,
        storageRemainingBytes: 0,
        storageQuotaBytes: 512 * 1024 * 1024,
        storageUsageBytes: 400 * 1024 * 1024,
        originRemainingBytes: 112 * 1024 * 1024,
        effectiveWritableBytes: 0,
        storageLimitReached: true,
        maintenanceNotice: '保持期限を超えたログ12件を自動削除しました。',
        error: 'ログ検証用の長いエラー表示です_ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789',
    },
    browserLogExportBusy: false,
    browserLogExportDisabled: false,
    browserLogExportTitle: '保存済みログをZIPで一括書き出し',
    browserLogPreparedArchive: null,
    browserLogNextExportBatch: null,
    browserLogExportNotice: null,
    browserLogExportError: null,
    browserLogMaintenanceOperation: null,
    browserLogMaintenanceError: null,
    rtcTimeStatus: {
        deviceTime: new Date(now - 123456),
        deviceEpochSeconds: Math.floor((now - 123456) / 1000),
        systemTimeAtRead: new Date(now),
        offsetMs: -123456,
        lastReadAt: now,
        supported: true,
        readError: 'RTC検証用の長いエラー表示です_ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789',
        syncState: 'failed',
        lastSyncAt: now - 30000,
        lastSyncOffsetMs: -123456,
        syncMessage: '同期失敗: layout regression fixture',
        zoneId: 367396520,
        zoneName: 'Asia/Tokyo',
        totalUtcOffsetMinutes: 540,
        standardUtcOffsetMinutes: 540,
        dstOffsetMinutes: 0,
        tzdbVersion: '2025b',
        rtcDetected: true,
        rtcReadable: true,
        utcValid: true,
        zoneConfigured: true,
        nvsPersisted: true,
        dstActive: false,
        operationGeneration: 1,
        lastOperation: 'sync_utc_and_zone',
        lastResult: 'ok',
        operationBusy: false,
        deviceError: false,
    },
    deviceModeStatus: {
        protocolVersion: 1,
        modeCode: 1,
        mode: 'i2cMeasure',
        flags: 0xff,
        phyCode: 0,
        phy: '1m',
        bleConnected: true,
        uartBridgeEnabled: true,
        i2cMeasureActive: true,
        commandMode: true,
        bootloaderMode: true,
        wifiPortalActive: true,
        stm32UpdateActive: true,
    },
    deviceModeLastReadAt: now,
    deviceModeNotifyActive: true,
    deviceModeSupported: true,
    i2cConfigStatus: {
        protocolVersion: 1,
        lastOpCode: 0,
        lastOp: 'read',
        resultCode: 0,
        result: 'ok',
        remoteCommandStatus: 0,
        remoteLastError: 0,
        configFlags: 0x03,
        nodeId: 101,
        avgCycle: 64,
        windDirInstallMode: 1,
        i2cAddress: 0x42,
        i2cSlaveEnabled: true,
        measurementIntervalMs: 100,
        localI2cError: 0,
        remoteRegisterVersion: 6,
        currentTargetI2cAddress: 0x42,
        rebootRequired: true,
        detected: true,
        configWriteSupported: true,
    },
    i2cConfigBusy: false,
    parseErrorStats: {
        count: 123,
        lastError: 'notify_payload_parse_error_ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789',
    },
    error: 'BLE_error_ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789',
    isSupported: true,
    platformInfo: {
        platform: 'ios',
        adapterType: 'Capacitor',
        browserName: 'WKWebView-layout-regression',
        secureContext: true,
        webBluetoothAvailable: false,
        isSupported: true,
    },
    currentThemeIndex: 4,
    themeGradient: 'linear-gradient(150deg, #1d3540, #294a57)',
    themeIsLight: false,
    onThemeChange: noop,
    onSyncTime: noop,
    onRefreshRtcTime: noop,
    onRefreshStm32FirmwareVersion: noop,
    onRefreshSampleMetadataStatus: noop,
    onRefreshDeviceHealthStatus: noop,
    onRefreshCapabilitiesStatus: noop,
    onRefreshLedBrightness: noop,
    onSetLedBrightness: noop,
    onRefreshLedWindReactive: noop,
    onSetLedWindReactive: noop,
    onRefreshDeviceResetStatus: noop,
    onResetDevice: async () => null,
    onRefreshOtaControlStatus: noopAsync,
    onWriteOtaControl: async () => null,
    onRefreshStm32UpdateControlStatus: noopAsync,
    onWriteStm32UpdateControl: async () => null,
    onRefreshCardStatus: noop,
    onRefreshCardLogDetailStatus: noop,
    onRefreshCardLogSettingsStatus: noop,
    onWriteCardLogSettings: noop,
    onBrowserLogIntervalMsChange: () => true,
    onPrepareBrowserLogExport: noop,
    onDeliverPreparedBrowserLogExport: noop,
    onPrepareNextBrowserLogExport: noop,
    onDiscardPreparedBrowserLogExport: noop,
    onRefreshBrowserLogs: noop,
    onDeleteBrowserLogSession: noop,
    onDeleteAllBrowserLogs: noop,
    onRefreshDeviceModeStatus: noop,
    onRefreshI2cConfigStatus: noop,
    onWriteI2cConfig: noop,
    onClearError: noop,
};
