import type { BLEParseErrorStats, BLEPlatformInfo, StandardSensorField } from '../../services/ble';
import type { BLECapabilitiesStatus, DeviceHealthStatus, DeviceInfo, DeviceModeStatus, DeviceResetStatus, DeviceResetTarget, I2cConfigStatus, I2cConfigWriteRequest, LEDBrightnessStatus, LEDWindReactiveConfig, LEDWindReactiveStatus, OtaControlOp, OtaControlStatus, RtcTimeStatus, SampleMetadataStatus, CardLogControlStatus, CardLogDetailStatus, CardLogSettingsStatus, CardLogSettingsWriteRequest, CardStatus, SensorData, Stm32FirmwareVersionStatus, Stm32UpdateControlOp, Stm32UpdateControlSessionBinding, Stm32UpdateControlStatus, } from '../../types/ble';
export type BLEConnectionState = 'disconnected' | 'scanning' | 'connecting' | 'connected';
export type BLEDataState = 'idle' | 'waiting' | 'live' | 'stale';
export interface BLEDeviceInfo {
    deviceId: string;
    name: string | null;
    rssi?: number;
    nodeId?: number;
}
export interface DemoFirmwareIdentityExpectation {
    version: string;
    revision: number;
    commit: string;
}
export type SensorFieldReceivedAt = Partial<Record<StandardSensorField, number>>;
export type TimelineSampleListener = (sample: SensorData) => void;
export interface SensorDisplayUpdate {
    latestSample: SensorData;
    standardFieldReceivedAt: SensorFieldReceivedAt;
    lastStandardReceivedAt: number | null;
}
export type DisplaySampleListener = (update: SensorDisplayUpdate) => void;
export interface UseBLEReturn {
    connectionState: BLEConnectionState;
    connectedDevice: BLEDeviceInfo | null;
    availableDevices: BLEDeviceInfo[];
    identifyingDeviceId: string | null;
    sensorData: SensorData | null;
    subscribeDisplaySamples: (listener: DisplaySampleListener) => () => void;
    subscribeTimelineSamples: (listener: TimelineSampleListener) => () => void;
    sensorFieldReceivedAt: SensorFieldReceivedAt;
    dataState: BLEDataState;
    lastSensorDataAt: number | null;
    deviceInfo: DeviceInfo | null;
    firmwareInfoBusy: boolean;
    firmwareInfoError: string | null;
    stm32FirmwareVersion: Stm32FirmwareVersionStatus | null;
    stm32FirmwareVersionLastReadAt: number | null;
    sampleMetadataStatus: SampleMetadataStatus | null;
    sampleMetadataLastReadAt: number | null;
    deviceHealthStatus: DeviceHealthStatus | null;
    deviceHealthLastReadAt: number | null;
    capabilitiesStatus: BLECapabilitiesStatus | null;
    capabilitiesLastReadAt: number | null;
    ledBrightnessStatus: LEDBrightnessStatus | null;
    ledBrightnessSupported: boolean | null;
    ledBrightnessBusy: boolean;
    ledWindReactiveStatus: LEDWindReactiveStatus | null;
    ledWindReactiveSupported: boolean | null;
    ledWindReactiveBusy: boolean;
    deviceResetStatus: DeviceResetStatus | null;
    deviceResetSupported: boolean | null;
    deviceResetBusy: boolean;
    otaControlStatus: OtaControlStatus | null;
    otaControlBusy: boolean;
    stm32UpdateControlStatus: Stm32UpdateControlStatus | null;
    stm32UpdateControlBusy: boolean;
    cardStatus: CardStatus | null;
    cardStatusLastReadAt: number | null;
    cardLogControlStatus: CardLogControlStatus | null;
    cardLogControlSupported: boolean | null;
    cardLogControlBusy: boolean;
    cardLogDetailStatus: CardLogDetailStatus | null;
    cardLogDetailLastReadAt: number | null;
    cardLogSettingsStatus: CardLogSettingsStatus | null;
    cardLogSettingsLastReadAt: number | null;
    cardLogSettingsBusy: boolean;
    rtcTimeStatus: RtcTimeStatus;
    deviceModeStatus: DeviceModeStatus | null;
    deviceModeLastReadAt: number | null;
    deviceModeNotifyActive: boolean;
    deviceModeSupported: boolean | null;
    i2cConfigStatus: I2cConfigStatus | null;
    i2cConfigSupported: boolean | null;
    i2cConfigBusy: boolean;
    parseErrorStats: BLEParseErrorStats;
    error: string | null;
    isSupported: boolean;
    platformInfo: BLEPlatformInfo | null;
    scanAndConnect: () => Promise<void>;
    cancelScan: () => Promise<void>;
    connectToDevice: (device: BLEDeviceInfo) => Promise<void>;
    verifyInstalledDemo: (expected: DemoFirmwareIdentityExpectation) => Promise<void>;
    identifyDevice: (device: BLEDeviceInfo) => Promise<void>;
    disconnect: () => Promise<void>;
    setSensorNotificationsPaused: (paused: boolean) => Promise<void>;
    syncTime: (zoneId: number) => Promise<void>;
    setRtcTimezone: (zoneId: number) => Promise<void>;
    refreshRtcTime: () => Promise<void>;
    refreshCardStatus: () => Promise<void>;
    setCardLogging: (enabled: boolean) => Promise<void>;
    writeCardLogSettings: (request: CardLogSettingsWriteRequest) => Promise<void>;
    refreshDeviceModeStatus: () => Promise<void>;
    refreshStm32FirmwareVersion: () => Promise<void>;
    refreshFirmwareVersions: () => Promise<void>;
    refreshSampleMetadataStatus: () => Promise<void>;
    refreshDeviceHealthStatus: () => Promise<void>;
    refreshCapabilitiesStatus: () => Promise<void>;
    refreshLedBrightness: () => Promise<void>;
    refreshLedWindReactive: () => Promise<void>;
    refreshDeviceResetStatus: () => Promise<void>;
    refreshOtaControlStatus: () => Promise<void>;
    refreshStm32UpdateControlStatus: () => Promise<void>;
    setLedBrightness: (brightness: number) => Promise<void>;
    setLedWindReactive: (config: LEDWindReactiveConfig) => Promise<void>;
    resetDevice: (target: DeviceResetTarget) => Promise<DeviceResetStatus | null>;
    writeOtaControl: (op: OtaControlOp) => Promise<OtaControlStatus | null>;
    writeStm32UpdateControl: (op: Stm32UpdateControlOp, binding?: Stm32UpdateControlSessionBinding) => Promise<Stm32UpdateControlStatus | null>;
    refreshI2cConfigStatus: () => Promise<void>;
    refreshCardLogDetailStatus: () => Promise<void>;
    refreshCardLogSettingsStatus: () => Promise<void>;
    writeI2cConfig: (request: I2cConfigWriteRequest) => Promise<boolean>;
    clearError: () => void;
}
export interface UseBLEOptions {
    diagnosticsActive?: boolean;
    backgroundSensorDisplayActive?: boolean;
}
