import type { BLECapabilitiesStatus, DeviceHealthStatus, DeviceInfo, DeviceModeStatus, DeviceResetStatus, DeviceResetTarget, I2cConfigStatus, I2cConfigWriteRequest, LEDBrightnessStatus, LEDWindReactiveConfig, LEDWindReactiveStatus, OtaControlOp, OtaControlStatus, RtcTimeStatus, SampleMetadataStatus, CardLogDetailStatus, CardLogSettingsStatus, CardLogSettingsWriteRequest, CardStatus, Stm32FirmwareVersionStatus, Stm32UpdateControlOp, Stm32UpdateControlSessionBinding, Stm32UpdateControlStatus, } from '../../types/ble';
import type { BLEConnectionState, BLEDataState, BLEDeviceInfo } from '../../hooks/useBLE';
import type { DemoFirmwareIdentityExpectation } from '../../hooks/ble/types';
import type { BLEParseErrorStats, BLEPlatformInfo } from '../../services/ble';
import type { BrowserLogPreparedArchive, BrowserLogStatus } from '../../services/browserLog';
import type { PointerEventHandler } from 'react';
export type SettingsCategory = 'overview' | 'appearance' | 'firmware' | 'time' | 'storage' | 'i2c' | 'sample' | 'info';
export type BLESettingsDrawerEntryMode = 'animated' | 'settled' | 'interactive';
export type BLESettingsDrawerPanelGestureHandlers = {
    onPointerDown: PointerEventHandler<HTMLElement>;
    onPointerMove: PointerEventHandler<HTMLElement>;
    onPointerUp: PointerEventHandler<HTMLElement>;
    onPointerCancel: PointerEventHandler<HTMLElement>;
    onLostPointerCapture: PointerEventHandler<HTMLElement>;
};
export interface BLESettingsDrawerProps {
    isOpen: boolean;
    entryMode?: BLESettingsDrawerEntryMode;
    isModalActive?: boolean;
    interactionProgress?: number;
    interactionOffsetPx?: number;
    interactionTransitionMs?: number;
    panelGestureHandlers?: BLESettingsDrawerPanelGestureHandlers;
    onDismiss: () => void;
    isUpsideDown?: boolean;
    connectionState: BLEConnectionState;
    dataState: BLEDataState;
    connectedDevice: BLEDeviceInfo | null;
    deviceInfo: DeviceInfo | null;
    stm32FirmwareVersion?: Stm32FirmwareVersionStatus | null;
    stm32FirmwareVersionLastReadAt?: number | null;
    sampleMetadataStatus?: SampleMetadataStatus | null;
    sampleMetadataLastReadAt?: number | null;
    deviceHealthStatus?: DeviceHealthStatus | null;
    deviceHealthLastReadAt?: number | null;
    capabilitiesStatus?: BLECapabilitiesStatus | null;
    capabilitiesLastReadAt?: number | null;
    ledBrightnessStatus?: LEDBrightnessStatus | null;
    ledBrightnessSupported?: boolean | null;
    ledBrightnessBusy?: boolean;
    ledWindReactiveStatus?: LEDWindReactiveStatus | null;
    ledWindReactiveSupported?: boolean | null;
    ledWindReactiveBusy?: boolean;
    deviceResetStatus?: DeviceResetStatus | null;
    deviceResetSupported?: boolean | null;
    deviceResetBusy?: boolean;
    otaControlStatus?: OtaControlStatus | null;
    otaControlBusy?: boolean;
    stm32UpdateControlStatus?: Stm32UpdateControlStatus | null;
    stm32UpdateControlBusy?: boolean;
    cardStatus: CardStatus | null;
    cardStatusLastReadAt?: number | null;
    cardLogDetailStatus?: CardLogDetailStatus | null;
    cardLogDetailLastReadAt?: number | null;
    cardLogSettingsStatus?: CardLogSettingsStatus | null;
    cardLogSettingsLastReadAt?: number | null;
    cardLogSettingsBusy?: boolean;
    browserLogIntervalMs: number;
    browserLogStatus: BrowserLogStatus;
    browserLogExportBusy: boolean;
    browserLogExportDisabled: boolean;
    browserLogExportTitle: string;
    browserLogPreparedArchive: BrowserLogPreparedArchive | null;
    browserLogNextExportBatch: {
        sessionId: string | null;
        batchIndex: number;
        batchCount: number;
    } | null;
    browserLogExportNotice: string | null;
    browserLogExportError: string | null;
    browserLogMaintenanceOperation: 'refresh' | 'delete-all' | string | null;
    browserLogMaintenanceError: string | null;
    rtcTimeStatus: RtcTimeStatus;
    deviceModeStatus: DeviceModeStatus | null;
    deviceModeLastReadAt?: number | null;
    deviceModeNotifyActive?: boolean;
    deviceModeSupported?: boolean | null;
    i2cConfigStatus: I2cConfigStatus | null;
    i2cConfigBusy: boolean;
    parseErrorStats: BLEParseErrorStats;
    error: string | null;
    isSupported: boolean;
    platformInfo: BLEPlatformInfo | null;
    currentThemeIndex: number;
    themeGradient?: string;
    themeIsLight?: boolean;
    onThemeChange: (themeIndex: number) => void;
    onSyncTime: (zoneId: number) => void;
    onSetRtcTimezone?: (zoneId: number) => void;
    onRefreshRtcTime: () => void;
    onRefreshStm32FirmwareVersion?: () => void;
    onRefreshFirmwareVersions?: () => void;
    firmwareInfoBusy?: boolean;
    firmwareInfoError?: string | null;
    onRefreshSampleMetadataStatus?: () => void;
    onRefreshDeviceHealthStatus?: () => void;
    onRefreshCapabilitiesStatus?: () => void;
    onRefreshLedBrightness?: () => void;
    onSetLedBrightness?: (brightness: number) => void;
    onRefreshLedWindReactive?: () => void;
    onSetLedWindReactive?: (config: LEDWindReactiveConfig) => void;
    onRefreshDeviceResetStatus?: () => void;
    onResetDevice?: (target: DeviceResetTarget) => Promise<DeviceResetStatus | null>;
    onRefreshOtaControlStatus?: () => Promise<void>;
    onWriteOtaControl?: (op: OtaControlOp) => Promise<OtaControlStatus | null>;
    onVerifyInstalledDemo?: (expected: DemoFirmwareIdentityExpectation) => Promise<void>;
    onRefreshStm32UpdateControlStatus?: () => Promise<void>;
    onWriteStm32UpdateControl?: (op: Stm32UpdateControlOp, binding?: Stm32UpdateControlSessionBinding) => Promise<Stm32UpdateControlStatus | null>;
    onRefreshCardStatus: () => void;
    onRefreshCardLogDetailStatus?: () => void;
    onRefreshCardLogSettingsStatus?: () => void;
    onWriteCardLogSettings?: (request: CardLogSettingsWriteRequest) => void;
    onBrowserLogIntervalMsChange: (intervalMs: number) => boolean;
    onPrepareBrowserLogExport: (scope?: string | string[]) => void;
    onDeliverPreparedBrowserLogExport: () => void;
    onPrepareNextBrowserLogExport: () => void;
    onDiscardPreparedBrowserLogExport: () => void;
    onRefreshBrowserLogs: () => void;
    onDeleteBrowserLogSession: (sessionId: string) => void;
    onDeleteAllBrowserLogs: () => void;
    onRefreshDeviceModeStatus: () => void;
    onRefreshI2cConfigStatus: () => void;
    onWriteI2cConfig: (request: I2cConfigWriteRequest) => boolean | void | Promise<boolean | void>;
    onClearError: () => void;
}
